---
apiVersion: v1
kind: Service
metadata:
  name: mdaas-activemq-artemis
  namespace: mdaas-engines-local
spec:
  ports:
    - name: stomp
      port: 61613
      targetPort: 61613
      nodePort: 31617
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 31672
    - name: web-console
      port: 8161
      targetPort: 8161
      nodePort: 30817
    - name: jmx
      port: 1099
      targetPort: 1099
      nodePort: 31099
    - name: rmi-registry
      port: 1098
      targetPort: 1098
      nodePort: 31098
  selector:
    app: mdaas-activemq-artemis
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: activemq-artemis-config
  namespace: mdaas-engines-local
data:
  broker.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <configuration xmlns="urn:activemq" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core">
        <name>artemis</name>
        <persistence-enabled>true</persistence-enabled>
        <journal-type>ASYNCIO</journal-type>
        <paging-directory>data/paging</paging-directory>
        <bindings-directory>data/bindings</bindings-directory>
        <journal-directory>data/journal</journal-directory>
        <large-messages-directory>data/large-messages</large-messages-directory>
        
        <!-- Scheduled messaging configuration -->
        <scheduled-message-timeout>3600000</scheduled-message-timeout>
        <scheduled-threads>5</scheduled-threads>
        
        <!-- Add the plugins section to enable the scheduler plugin -->
        <plugins>
          <plugin class-name="org.apache.activemq.artemis.core.server.plugin.impl.LoggingActiveMQServerPlugin"/>
          <plugin class-name="org.apache.activemq.artemis.core.server.impl.ScheduledDeliveryPlugin"/>
        </plugins>
        
        <!-- Message expiry configurations -->
        <message-expiry-scan-period>30000</message-expiry-scan-period>
        <message-expiry-thread-priority>3</message-expiry-thread-priority>
        
        <!-- Security settings -->
        <security-enabled>true</security-enabled>
        
        <!-- Memory settings -->
        <global-max-size>1G</global-max-size>
        
        <acceptors>
          <!-- STOMP Acceptor -->
          <acceptor name="stomp">tcp://0.0.0.0:61613?protocols=STOMP</acceptor>
          
          <!-- Dedicated AMQP Acceptor -->
          <acceptor name="amqp">tcp://0.0.0.0:5672?protocols=AMQP;tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;amqpCredits=1000;amqpLowCredits=300;amqpMinLargeMessageSize=102400;useEpoll=true</acceptor>
          
          <!-- Core protocols Acceptor -->
          <acceptor name="artemis">tcp://0.0.0.0:61616?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE;useEpoll=true;amqpCredits=1000;amqpLowCredits=300</acceptor>
          
          <!-- Web Console Acceptor -->
          <acceptor name="artemis-http">tcp://0.0.0.0:8161?protocols=HTTP</acceptor>
        </acceptors>
        
        <address-settings>
          <!-- Default for catch all -->
          <address-setting match="#">
            <dead-letter-address>DLQ</dead-letter-address>
            <expiry-address>ExpiryQueue</expiry-address>
            <redelivery-delay>0</redelivery-delay>
            <max-size-bytes>-1</max-size-bytes>
            <message-counter-history-day-limit>10</message-counter-history-day-limit>
            <address-full-policy>PAGE</address-full-policy>
            <auto-create-queues>true</auto-create-queues>
            <auto-create-addresses>true</auto-create-addresses>
            <auto-create-jms-queues>true</auto-create-jms-queues>
            <auto-create-jms-topics>true</auto-create-jms-topics>
          </address-setting>
        </address-settings>
        
        <addresses>
          <address name="DLQ">
            <anycast>
              <queue name="DLQ"/>
            </anycast>
          </address>
          <address name="ExpiryQueue">
            <anycast>
              <queue name="ExpiryQueue"/>
            </anycast>
          </address>
        </addresses>
      </core>
    </configuration>

  bootstrap.xml: |
    <broker xmlns="http://activemq.apache.org/schema">
      <web bind="http://0.0.0.0:8161" path="web">
        <app url="console" war="console.war"/>
        <app url="metrics" war="metrics.war"/>
        <!-- Deploy Jolokia for HTTP/JSON JMX access -->
        <app url="jolokia" war="jolokia.war"/>
        <!-- Enable REST API for management -->
        <app url="api" war="artemis-plugin.war"/>
      </web>
      <jaas-security domain="activemq"/>
    </broker>

  management.xml: |
    <management-context xmlns="http://activemq.apache.org/schema">
      <connector connector-port="1099"/>
      <connector connector-host="0.0.0.0"/>
      <connector rmi-registry-port="1098"/>
      <connector rmi-registry-host="0.0.0.0"/>
      <jmx-use-broker-name>true</jmx-use-broker-name>
      <jmx-domain>org.apache.activemq.artemis</jmx-domain>
      <!-- Updated attribute name to "auth" -->
      <connector auth="false"/>
      <authorisation>
        <!-- Allow anyone to connect to the JMX connector -->
        <entry domain="org.apache.activemq.artemis">
          <access method="*" roles="admin"/>
        </entry>
      </authorisation>
    </management-context>

  login.config: |
    activemq {
      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule required
          org.apache.activemq.jaas.properties.user="artemis-users.properties"
          org.apache.activemq.jaas.properties.role="artemis-roles.properties"
          reload=true;
    };

  artemis-users.properties: |
    admin=admin,admin

  artemis-roles.properties: |
    admin=admin

  jmx-access.properties: |
    admin readwrite

  jmx-password.properties: |
    admin=admin

  broker.properties: |
    # Additional broker properties
    # Enable message ID and timestamp
    messageid.enabled=true
    timestamp.enabled=true
    # Enable REST API
    rest.enabled=true
    # AMQP specific configurations
    amqp.sasl.enabled=true

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mdaas-activemq-artemis
  namespace: mdaas-engines-local
spec:
  replicas: 1
  serviceName: mdaas-activemq-artemis
  selector:
    matchLabels:
      app: mdaas-activemq-artemis
  template:
    metadata:
      labels:
        app: mdaas-activemq-artemis
    spec:
      initContainers:
      - name: init-artemis-dirs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/lib/artemis/data/journal /var/lib/artemis/data/bindings /var/lib/artemis/data/paging /var/lib/artemis/data/large-messages && chmod -R 777 /var/lib/artemis/data']
        volumeMounts:
        - name: artemis-persistent-storage
          mountPath: /var/lib/artemis/data
      - name: init-jolokia
        image: curlimages/curl:7.88.1
        command: ['sh', '-c', 'curl -L https://repo1.maven.org/maven2/org/jolokia/jolokia-war/1.7.2/jolokia-war-1.7.2.war -o /opt/jolokia/jolokia.war']
        volumeMounts:
        - name: jolokia-war
          mountPath: /opt/jolokia
      containers:
      - name: mdaas-activemq-artemis
        image: apache/activemq-artemis:2.30.0
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - name: stomp
            containerPort: 61613
            protocol: TCP
          - name: amqp
            containerPort: 5672
            protocol: TCP
          - name: core
            containerPort: 61616
            protocol: TCP
          - name: web-console
            containerPort: 8161
            protocol: TCP
          - name: jmx
            containerPort: 1099
            protocol: TCP
          - name: rmi-registry
            containerPort: 1098
            protocol: TCP
        volumeMounts:
        - name: artemis-persistent-storage
          mountPath: /var/lib/artemis/data
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/broker.xml
          subPath: broker.xml
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/bootstrap.xml
          subPath: bootstrap.xml
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/management.xml
          subPath: management.xml
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/login.config
          subPath: login.config
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/artemis-users.properties
          subPath: artemis-users.properties
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/artemis-roles.properties
          subPath: artemis-roles.properties
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/jmx.access
          subPath: jmx-access.properties
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/jmx.password
          subPath: jmx-password.properties
        - name: artemis-config-volume
          mountPath: /var/lib/artemis/etc/broker.properties
          subPath: broker.properties
        - name: jolokia-war
          mountPath: /var/lib/artemis/web/jolokia.war
          subPath: jolokia.war
        env:
          - name: JAVA_OPTS
            value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=true -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.access.file=/var/lib/artemis/etc/jmx.access -Dcom.sun.management.jmxremote.password.file=/var/lib/artemis/etc/jmx.password"
      volumes:
      - name: artemis-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-mdaas-activemq-artemis
      - name: artemis-config-volume
        configMap:
          name: activemq-artemis-config
      - name: jolokia-war
        emptyDir: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mdaas-activemq-artemis
  namespace: mdaas-engines-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi