apiVersion: v1
kind: Service
metadata:
  name: {{ include "active-mq.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "active-mq.name" . }}
spec:
  clusterIP: None
  ports:
    - port: 7800
      targetPort: 7800
      protocol: TCP
      name: jgroups
  selector:
    app: {{ include "active-mq.name" . }} 