# templates/hpa.yaml
{{- if .Values.triggerAuth }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.triggerAuth.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretTargetRef:
    {{- with .Values.triggerAuth.secretTargetRef }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
---
{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "active-mq.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "active-mq.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    # CPU Trigger
    - type: cpu
      metadata:
        type: Utilization
        value: "80"
    # Memory Trigger
    - type: memory
      metadata:
        type: Utilization
        value: "80"
    # Queue Triggers
    {{- range .Values.keda.queues }}
    - type: activemq
      metadata:
        managementEndpoint: "http://{{ include "active-mq.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.keda.broker.managementPort }}"
        queueName: {{ .name | quote }}
        queueLength: {{ .length | quote }}
        activationQueueLength: {{ .activationLength | quote }}
        brokerName: {{ $.Values.keda.broker.name | quote }}
        brokerAddress: "tcp://{{ include "active-mq.fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.keda.broker.corePort }}"
      authenticationRef:
        name: {{ $.Values.triggerAuth.name | quote }}
    {{- end }}
{{- end }}
