apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "active-mq.fullname" . }}-jgroups
  namespace: {{ .Release.Namespace }}
data:
  jgroups-kubernetes.xml: |-
    <config xmlns="urn:org:jgroups"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
        <TCP bind_addr="${jgroups.bind_addr:SITE_LOCAL}"
             bind_port="${jgroups.bind_port:7800}"
             enable_diagnostics="false"
             thread_naming_pattern="pl"
             send_buf_size="640k"
             sock_conn_timeout="300"
             bundler_type="no-bundler"
             
             thread_pool.min_threads="${jgroups.thread_pool.min_threads:0}"
             thread_pool.max_threads="${jgroups.thread_pool.max_threads:200}"
             thread_pool.keep_alive_time="60000"
        />
        <dns.DNS_PING
             dns_query="{{include "active-mq.fullname" .}}-headless.${KUBERNETES_NAMESPACE}.svc.cluster.local"
             async_discovery="true"
        />
        <MERGE3 min_interval="10000"
                max_interval="30000"
        />
        <FD_SOCK/>
        <FD_ALL timeout="60000"
                interval="15000"
                timeout_check_interval="5000"
        />
        <VERIFY_SUSPECT timeout="5000"/>
        <pbcast.NAKACK2 use_mcast_xmit="false"
                        discard_delivered_msgs="true"
        />
        <UNICAST3/>
        <pbcast.STABLE stability_delay="500"
                       desired_avg_gossip="5000"
                       max_bytes="1M"
        />
        <pbcast.GMS print_local_addr="true"
                    join_timeout="3000"
        />
        <UFC max_credits="4m"
             min_threshold="0.40"
        />
        <MFC max_credits="4m"
             min_threshold="0.40"
        />
        <FRAG3/>
    </config> 