{{- if .Values.monitoring.jmx.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jmx-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Format: "<username> readwrite" - Grants read/write permissions to the specified user
  jmxremote.access: {{ printf "%s readwrite" (include "active-mq.jmxUsername" .) | b64enc | quote }}
  # Format: "<username> <password>" - Credentials for JMX authentication
  jmxremote.password: {{ printf "%s %s" (include "active-mq.jmxUsername" .) (include "active-mq.jmxPassword" .) | b64enc | quote }}
{{- end }}
