# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "active-mq.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass.create }}
  storageClassName: {{ .Values.persistence.storageClass.name }}
  {{- end }}