{{- if and .Values.authentication.create (not .Values.authentication.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "active-mq.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "active-mq.labels" . | nindent 4 }}
type: Opaque
data:
  # Use specified key names or default to ACTIVEMQ_USER/ACTIVEMQ_PASSWORD
  {{ default "ACTIVEMQ_USER" .Values.authentication.secretKeys.username }}: {{- if and (eq .Values.authentication.defaultUsername "admin") (eq .Values.authentication.defaultPassword "") .Release.IsInstall }}
    {{ randAlphaNum 8 | b64enc | quote }}  # Generate random username only during install if both are default
  {{- else }}
    {{- if .Values.authentication.defaultUsername | ne "admin" }}
      {{ .Values.authentication.defaultUsername | b64enc | quote }}  # Use provided username if not empty
    {{- else }}
      {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-credentials" (include "active-mq.fullname" .)) }}
      {{- if $existingSecret }}
        {{ index $existingSecret.data (default "ACTIVEMQ_USER" .Values.authentication.secretKeys.username) | quote }}  # Use existing username if available (from upgrade)
      {{- else }}
        {{ default "admin" .Values.authentication.defaultUsername | b64enc | quote }}  # Fallback to admin or configured default
      {{- end }}
    {{- end }}
  {{- end }}
  
  # Use specified password key name or default
  {{ default "ACTIVEMQ_PASSWORD" .Values.authentication.secretKeys.password }}: {{- if and (eq .Values.authentication.defaultUsername "admin") (eq .Values.authentication.defaultPassword "") .Release.IsInstall }}
    {{ randAlphaNum 16 | b64enc | quote }}  # Generate random password only during install if both are default
  {{- else }}
    {{- if .Values.authentication.defaultPassword | ne "" }}
      {{ .Values.authentication.defaultPassword | b64enc | quote }}  # Use provided password if not empty
    {{- else }}
      {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-credentials" (include "active-mq.fullname" .)) }}
      {{- if $existingSecret }}
        {{ index $existingSecret.data (default "ACTIVEMQ_PASSWORD" .Values.authentication.secretKeys.password) | quote }}  # Use existing password if available (from upgrade)
      {{- else }}
        {{ randAlphaNum 16 | b64enc | quote }}  # Fallback to generating a password if no secret found
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}