{{- if and .Values.authentication.create (not .Values.authentication.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "active-mq.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "active-mq.labels" . | nindent 4 }}
type: Opaque
data:
  # Use default admin username or the one specified in values
  ACTIVEMQ_USER: {{ default "admin" .Values.authentication.defaultUsername | b64enc | quote }}
  
  # Use specified password or generate a random one if not provided
  ACTIVEMQ_PASSWORD: {{ default (randAlphaNum 16) .Values.authentication.defaultPassword | b64enc | quote }}
{{- end }} 