{{- if and .Values.authentication.create (not .Values.authentication.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "active-mq.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "active-mq.labels" . | nindent 4 }}
type: Opaque
data:
  # Use specified key names or default to ACTIVEMQ_USER/ACTIVEMQ_PASSWORD
  {{ default "ACTIVEMQ_USER" .Values.authentication.secretKeys.username }}: {{ default "admin" .Values.authentication.defaultUsername | b64enc | quote }}
  
  # Use specified password key name or default
  {{ default "ACTIVEMQ_PASSWORD" .Values.authentication.secretKeys.password }}: {{ default (randAlphaNum 16) .Values.authentication.defaultPassword | b64enc | quote }}
{{- end }}