# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "active-mq.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: prometheus
      port: 9404
      targetPort: 9404
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: {{ include "active-mq.name" . }}