apiVersion: v1
kind: Service
metadata:
  name: {{ include "active-mq.fullname" . }}-slave
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "active-mq.name" . }}
    role: slave
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - port: 9404
      targetPort: 9404
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app: {{ include "active-mq.name" . }}
    role: slave 