{{- if .Values.persistence.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "active-mq.storageClassName" . }}
  labels:
    {{- include "active-mq.labels" . | nindent 4 }}
{{- with .Values.persistence.storageClass.provisioner }}
provisioner: {{ . }}
{{- end }}
{{- with .Values.persistence.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.persistence.storageClass.reclaimPolicy }}
reclaimPolicy: {{ . }}
{{- end }}
{{- with .Values.persistence.storageClass.volumeBindingMode }}
volumeBindingMode: {{ . }}
{{- end }}
{{- end }} 